[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
libc = "0.2"
base64 = "0.21"
chacha20 = "0.8"
sled = "0.34"
once_cell = "1.21.3"
tempfile = "3.20.0"

[lib]
crate-type = ["staticlib"]
